# REQUIRED CHANGES
# Edit next line to provide your own name.
title: Molly Maluhia | Professional Portfolio
# Edit next line, replacing 'techfolios' with your github username
url: "https://techfolios.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: "/template"

# OPTIONAL CHANGES
## Specify the theme using any of the css files in css/techfolio-theme
techfolio-theme: default.css
## Specify the formatting for triple backquote code sections.
rouge-theme: github.css

# DON'T CHANGE THE FOLLOWING (unless you know what you're doing)
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist
